language: python
python:
    - "2.7"
    - "3.6"
install:
    - "pip install -r requirements.txt"
    - "pip install -r dev-requirements.txt"
script:
    - python app.py -z tests/testarchive.zip --test
